# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vectordb.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'vectordb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evectordb.proto\x12\x06vector\"/\n\rInsertRequest\x12\x0e\n\x06vec_id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"2\n\x0bInsertReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bshard_index\x18\x02 \x01(\x05\")\n\x0cQueryRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\",\n\nQueryReply\x12\x0b\n\x03ids\x18\x01 \x03(\x05\x12\x11\n\tdistances\x18\x02 \x03(\x02\"\x0e\n\x0cTrainRequest\"\x1c\n\nTrainReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa6\x01\n\x08VectorDB\x12\x34\n\x06Insert\x12\x15.vector.InsertRequest\x1a\x13.vector.InsertReply\x12\x31\n\x05Query\x12\x14.vector.QueryRequest\x1a\x12.vector.QueryReply\x12\x31\n\x05Train\x12\x14.vector.TrainRequest\x1a\x12.vector.TrainReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectordb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST']._serialized_start=26
  _globals['_INSERTREQUEST']._serialized_end=73
  _globals['_INSERTREPLY']._serialized_start=75
  _globals['_INSERTREPLY']._serialized_end=125
  _globals['_QUERYREQUEST']._serialized_start=127
  _globals['_QUERYREQUEST']._serialized_end=168
  _globals['_QUERYREPLY']._serialized_start=170
  _globals['_QUERYREPLY']._serialized_end=214
  _globals['_TRAINREQUEST']._serialized_start=216
  _globals['_TRAINREQUEST']._serialized_end=230
  _globals['_TRAINREPLY']._serialized_start=232
  _globals['_TRAINREPLY']._serialized_end=260
  _globals['_VECTORDB']._serialized_start=263
  _globals['_VECTORDB']._serialized_end=429
# @@protoc_insertion_point(module_scope)
